### ISSUE TITLE
Python関連

### ISSUE THREAD

**Issue by imyutaro** [imyutaro/note#9]
## ryeメモ

`pip --index-url` （ `pip install -i` ）でインストールするようなものは、`pyproject.toml` に以下のように記述する。

```toml
...
[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
...
```

https://github.com/imyutaro/ml_chatbot/issues/1
